slam_toolbox:
  ros__parameters:
    # 1. 시뮬레이터 시간 동기화
    use_sim_time: true

    # 2. 로컬라이제이션 모드 켜기
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_region_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # 🚨 모드 설정 (가장 중요)
    mode: localization

    # 🚨 기존에 따놓은 맵 경로 (확장자 .yaml 쓰면 절대 안 됨!!!)
    map_file_name: /home/inyup/colcon_ws/src/cap_sim_2026/maps/hex_robot_map # <--- 확장자 빼고!
    map_start_pose: [0.0, 0.0, 0.0]  # 초기 위치 설정
    map_start_at_dock: true

    minimum_travel_distance: 0.1   
    minimum_travel_heading: 0.2 

    # 🚨 [추가] 2. 기존 맵 비틀기(최적화) 절대 금지!
    do_loop_closing: false

    # 🚨 [추가] 3. 쓸데없이 맵 다시 그려서 쏘지 마! (10초에 한 번만 쏴)
    map_update_interval: 10.0

    # 3. TF 뼈대 설정
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    
    # 4. 아커만 특화 세팅 (기둥 사이를 지날 때 오돔을 맹신하게 만듦)
    use_map_saver: false
    map_update_interval: 1.0  # (기존 5.0) 맵 퍼블리시 주기
    resolution: 0.05
    max_laser_range: 15.0     # 라이다가 멀리 있는 기둥을 볼 수 있게 시야 확장
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000

    # 라이다 매칭 민감도 조절
    correlation_search_space_dimension: 0.8
    correlation_search_space_resolution: 0.05
    correlation_search_space_smear_deviation: 0.1

    minimum_time_between_scans: 0.1
    use_scan_matching: true
    
    # 🚨 오도메트리(바퀴+IMU) 신뢰도 대폭 향상
    # 기둥 사이에서 라이다가 안 맞을 때, EKF가 계산한 위치를 꽉 잡고 버팀
    odom_match_search_minimum_m: 0.3
    odom_match_search_minimum_rad: 0.2
